# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 587445dd42594adbfefa3cce8f0df51d09badf6c33beb6fe635c1c6f454df83904f27fa16b18928da5e18951cb7427fde1c93307d3269312260506a8e8ce11a1

test:
  secret_key_base: ca3b16be8ae5a440d222e0e1ee859cb94ffff01d34d58e714a4fccef7b130604086d0bc4b5bf68ab266dfe38d94614337eb9170612a99cca64d42d6875873b22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
